// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Domain.Entities.Appointment", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<string>("ClientId").IsRequired(false).HasColumnName("clientId");
            b.Property<DateTime>("EndsAt").IsRequired().HasColumnName("endsAt");
            b.Property<string>("Location").IsRequired(false).HasColumnName("location");
            b.Property<string>("Notes").IsRequired(false).HasColumnName("notes");
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professionalId");
            b.Property<string>("ServiceId").IsRequired(false).HasColumnName("serviceId");
            b.Property<DateTime>("StartsAt").IsRequired().HasColumnName("startsAt");
            b.Property<string>("Status").IsRequired().HasColumnName("status");
            b.HasKey("Id");
            b.HasIndex("ClientId").HasDatabaseName("IX_Appointment_clientId");
            b.HasIndex("ProfessionalId").HasDatabaseName("IX_Appointment_professionalId");
            b.HasIndex("ProfessionalId", "StartsAt", "Status").HasDatabaseName("IX_Appointment_professionalId_startsAt_status");
            b.ToTable("Appointment");
        });

        modelBuilder.Entity("Domain.Entities.Conversation", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<string>("ClientId").IsRequired().HasColumnName("clientId");
            b.Property<DateTime?>("ClientLastReadAt").HasColumnName("clientLastReadAt");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.Property<string>("OrderId").IsRequired(false).HasColumnName("orderId");
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professionalId");
            b.Property<DateTime?>("ProfessionalLastReadAt").HasColumnName("professionalLastReadAt");
            b.HasKey("Id");
            b.HasIndex("ClientId").HasDatabaseName("IX_Conversation_clientId");
            b.HasIndex("ClientId", "ProfessionalId").HasDatabaseName("IX_Conversation_clientId_professionalId");
            b.HasIndex("OrderId").IsUnique();
            b.HasIndex("ProfessionalId").HasDatabaseName("IX_Conversation_professionalId");
            b.ToTable("Conversation");
        });

        modelBuilder.Entity("Domain.Entities.Message", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<string>("ConversationId").IsRequired().HasColumnName("conversationId");
            b.Property<string>("SenderId").IsRequired().HasColumnName("senderId");
            b.Property<DateTime>("SentAt").IsRequired().HasColumnName("sentAt");
            b.Property<string>("Text").IsRequired().HasColumnName("text");
            b.HasKey("Id");
            b.HasIndex("ConversationId").HasDatabaseName("IX_Message_conversationId");
            b.HasIndex("ConversationId", "SentAt").HasDatabaseName("IX_Message_conversationId_sentAt");
            b.ToTable("Message");
        });

        modelBuilder.Entity("Domain.Entities.Order", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<string>("ClientId").IsRequired().HasColumnName("clientId");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.Property<DateTime?>("Date").HasColumnName("date");
            b.Property<string>("Description").IsRequired(false).HasColumnName("description");
            b.Property<string>("Location").IsRequired(false).HasColumnName("location");
            b.Property<string>("ServiceId").IsRequired().HasColumnName("serviceId");
            b.Property<string>("Status").IsRequired().HasColumnName("status").HasDefaultValue("aberto");
            // Phase 1 fields
            b.Property<string>("ProfessionalId").IsRequired(false).HasColumnName("professionalId");
            b.Property<int?>("TierId").HasColumnName("tierId");
            b.Property<string>("Origin").IsRequired(false).HasColumnName("origin");
            b.Property<string>("ProposalId").IsRequired(false).HasColumnName("proposalId");
            b.Property<string>("AppointmentId").IsRequired(false).HasColumnName("appointmentId");
            b.Property<string>("ConversationId").IsRequired(false).HasColumnName("conversationId");
            b.Property<int?>("PriceTotalCents").HasColumnName("priceTotalCents");
            b.Property<int?>("SignalCents").HasColumnName("signalCents");
            b.Property<int?>("BalanceCents").HasColumnName("balanceCents");
            b.Property<int>("Installments").IsRequired().HasColumnName("installments").HasDefaultValue(1);
            b.Property<string>("PaymentMethod").IsRequired(false).HasColumnName("paymentMethod");
            b.Property<string>("AddressId").IsRequired(false).HasColumnName("addressId");
            b.Property<string>("Scope").IsRequired(false).HasColumnName("scope");
            b.Property<DateTime?>("ScheduledAt").HasColumnName("scheduledAt");
            b.Property<DateTime?>("CompletedAt").HasColumnName("completedAt");
            b.Property<DateTime?>("CancelledAt").HasColumnName("cancelledAt");
            b.Property<string>("CancelledBy").IsRequired(false).HasColumnName("cancelledBy");
            b.Property<string>("CancellationReason").IsRequired(false).HasColumnName("cancellationReason");
            b.Property<DateTime?>("AutoConfirmAt").HasColumnName("autoConfirmAt");
            // Service address snapshot
            b.Property<string>("SvcAddrZipCode").IsRequired(false).HasColumnName("svcAddrZipCode");
            b.Property<string>("SvcAddrStreet").IsRequired(false).HasColumnName("svcAddrStreet");
            b.Property<string>("SvcAddrNumber").IsRequired(false).HasColumnName("svcAddrNumber");
            b.Property<string>("SvcAddrNeighborhood").IsRequired(false).HasColumnName("svcAddrNeighborhood");
            b.Property<string>("SvcAddrCity").IsRequired(false).HasColumnName("svcAddrCity");
            b.Property<string>("SvcAddrState").IsRequired(false).HasColumnName("svcAddrState");
            b.Property<string>("SvcAddrComplement").IsRequired(false).HasColumnName("svcAddrComplement");
            b.Property<string>("SvcAddrReference").IsRequired(false).HasColumnName("svcAddrReference");
            // Recurring plan FK
            b.Property<string>("RecurringPlanId").IsRequired(false).HasColumnName("recurringPlanId");
            // MP Integration
            b.Property<decimal>("PlatformFeePercent").IsRequired().HasColumnName("platformFeePercent").HasColumnType("numeric(5,2)").HasDefaultValue(10.00m);
            b.Property<int>("PlatformFeeCents").IsRequired().HasColumnName("platformFeeCents").HasDefaultValue(0);
            b.Property<int>("GatewayFeeCents").IsRequired().HasColumnName("gatewayFeeCents").HasDefaultValue(0);
            b.Property<string>("PaymentStatus").IsRequired(false).HasColumnName("paymentStatus").HasDefaultValue("unpaid");
            b.Property<string>("MpPreferenceId").IsRequired(false).HasColumnName("mpPreferenceId");
            b.HasKey("Id");
            b.HasIndex("ClientId").HasDatabaseName("IX_Order_clientId");
            b.HasIndex("ClientId", "CreatedAt").HasDatabaseName("IX_Order_clientId_createdAt");
            b.HasIndex("ServiceId").HasDatabaseName("IX_Order_serviceId");
            b.HasIndex("Status").HasDatabaseName("IX_Order_status");
            b.HasIndex("ProfessionalId").HasDatabaseName("IX_Order_professionalId");
            b.HasIndex("AutoConfirmAt").HasDatabaseName("IX_Order_autoConfirmAt");
            b.HasIndex("RecurringPlanId")
                .HasFilter("\"recurringPlanId\" IS NOT NULL")
                .HasDatabaseName("IX_Order_recurringPlanId");
            b.HasIndex("MpPreferenceId")
                .HasFilter("\"mpPreferenceId\" IS NOT NULL")
                .HasDatabaseName("IX_Order_mpPreferenceId");
            b.ToTable("Order");
        });

        modelBuilder.Entity("Domain.Entities.Proposal", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<string>("OrderId").IsRequired(false).HasColumnName("order_id");
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professional_id");
            b.Property<string>("ClientId").IsRequired().HasColumnName("client_id");
            b.Property<string>("ServiceId").IsRequired().HasColumnName("service_id");
            b.Property<string>("ProfessionalServiceId").IsRequired(false).HasColumnName("professional_service_id");
            b.Property<string>("ConversationId").IsRequired(false).HasColumnName("conversation_id");
            b.Property<string>("Scope").IsRequired().HasColumnName("scope");
            b.Property<string>("IncludesDescription").IsRequired(false).HasColumnName("includes_description");
            b.Property<string>("ExcludesDescription").IsRequired(false).HasColumnName("excludes_description");
            b.Property<int>("PriceTotalCents").IsRequired().HasColumnName("price_total_cents");
            b.Property<string>("PriceByStage").IsRequired(false).HasColumnName("price_by_stage").HasColumnType("jsonb");
            b.Property<string>("DurationEstimate").IsRequired(false).HasColumnName("duration_estimate");
            b.Property<DateTime?>("SuggestedDatetime").HasColumnName("suggested_datetime");
            b.Property<int>("VisitFeeCents").IsRequired().HasColumnName("visit_fee_cents").HasDefaultValue(0);
            b.Property<DateTime>("ValidUntil").IsRequired().HasColumnName("valid_until");
            b.Property<string>("Status").IsRequired().HasColumnName("status").HasDefaultValue("draft");
            b.Property<string>("RejectionReason").IsRequired(false).HasColumnName("rejection_reason");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("created_at");
            b.Property<DateTime>("UpdatedAt").IsRequired().HasColumnName("updated_at");
            b.HasKey("Id");
            b.HasIndex("OrderId").HasDatabaseName("IX_proposal_order_id");
            b.HasIndex("ProfessionalId").HasDatabaseName("IX_proposal_professional_id");
            b.HasIndex("ClientId").HasDatabaseName("IX_proposal_client_id");
            b.HasIndex("ConversationId").HasDatabaseName("IX_proposal_conversation_id");
            b.HasIndex("Status").HasDatabaseName("IX_proposal_status");
            b.HasIndex("ValidUntil").HasDatabaseName("IX_proposal_valid_until");
            b.ToTable("proposal");
        });

        modelBuilder.Entity("Domain.Entities.OrderTimeline", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<string>("OrderId").IsRequired().HasColumnName("order_id");
            b.Property<string>("EventType").IsRequired().HasColumnName("event_type");
            b.Property<string>("ActorId").IsRequired(false).HasColumnName("actor_id");
            b.Property<string>("ActorRole").IsRequired(false).HasColumnName("actor_role");
            b.Property<string>("Metadata").IsRequired(false).HasColumnName("metadata").HasColumnType("jsonb");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("created_at");
            b.HasKey("Id");
            b.HasIndex("OrderId", "CreatedAt").HasDatabaseName("IX_order_timeline_order_id_created_at");
            b.HasIndex("EventType").HasDatabaseName("IX_order_timeline_event_type");
            b.ToTable("order_timeline");
        });

        modelBuilder.Entity("Domain.Entities.Professional", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<bool>("Active").IsRequired().HasColumnName("active").HasDefaultValue(true);
            b.Property<bool?>("AllowInstantBooking").HasColumnName("allowInstantBooking");
            b.Property<string>("AvatarUrl").IsRequired(false).HasColumnName("avatarUrl");
            b.Property<string>("AvailabilityText").IsRequired(false).HasColumnName("availabilityText");
            b.Property<string>("Bio").IsRequired(false).HasColumnName("bio");
            b.Property<int>("CompletedJobsCount").IsRequired().HasColumnName("completedJobsCount").HasDefaultValue(0);
            b.Property<int?>("LeadTimeMinutes").HasColumnName("leadTimeMinutes");
            b.Property<int?>("MaxAdvanceDays").HasColumnName("maxAdvanceDays");
            b.Property<double?>("Rating").HasColumnName("rating");
            b.Property<int?>("SlotMinutes").HasColumnName("slotMinutes");
            b.Property<string>("UserId").IsRequired().HasColumnName("userId");
            b.Property<string>("EntityType").IsRequired(false).HasColumnName("entityType");
            b.Property<string>("DocumentNumber").IsRequired(false).HasColumnName("documentNumber");
            b.Property<int?>("YearsOfExperience").HasColumnName("yearsOfExperience");
            b.Property<string[]>("Specialties").HasColumnName("specialties").HasColumnType("text[]");
            b.Property<double?>("ResponseRate").HasColumnName("responseRate");
            b.Property<int?>("AvgResponseTimeMinutes").HasColumnName("avgResponseTimeMinutes");
            b.Property<double?>("CompletionRate").HasColumnName("completionRate");
            b.Property<string>("VerificationStatus").IsRequired().HasColumnName("verificationStatus").HasDefaultValue("pending");
            b.Property<string>("Badges").IsRequired(false).HasColumnName("badges");
            b.Property<int>("BufferMinutes").IsRequired().HasColumnName("bufferMinutes").HasDefaultValue(0);
            // MP Integration
            b.Property<bool>("MpConnected").IsRequired().HasColumnName("mpConnected").HasDefaultValue(false);
            b.Property<DateTime?>("MpConnectedAt").HasColumnName("mpConnectedAt");
            b.HasKey("Id");
            b.HasIndex("Active", "Rating").HasDatabaseName("IX_Professional_active_rating");
            b.HasIndex("UserId").HasDatabaseName("IX_Professional_userId");
            b.HasIndex("MpConnected")
                .HasFilter("\"mpConnected\" = true")
                .HasDatabaseName("IX_Professional_mpConnected");
            b.ToTable("Professional");
        });

        modelBuilder.Entity("Domain.Entities.ProfessionalAvailability", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<bool>("Active").IsRequired().HasColumnName("active").HasDefaultValue(true);
            b.Property<int>("EndMinutes").IsRequired().HasColumnName("endMinutes");
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professionalId");
            b.Property<int>("StartMinutes").IsRequired().HasColumnName("startMinutes");
            b.Property<int>("Weekday").IsRequired().HasColumnName("weekday");
            b.HasKey("Id");
            b.HasIndex("ProfessionalId", "Weekday").HasDatabaseName("IX_ProfessionalAvailability_professionalId_weekday");
            b.ToTable("ProfessionalAvailability");
        });

        modelBuilder.Entity("Domain.Entities.ProfessionalBlock", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.Property<DateTime>("EndsAt").IsRequired().HasColumnName("endsAt");
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professionalId");
            b.Property<string>("Reason").IsRequired(false).HasColumnName("reason");
            b.Property<DateTime>("StartsAt").IsRequired().HasColumnName("startsAt");
            b.HasKey("Id");
            b.HasIndex("ProfessionalId", "StartsAt", "EndsAt").HasDatabaseName("IX_ProfessionalBlock_professionalId_startsAt_endsAt");
            b.ToTable("ProfessionalBlock");
        });

        modelBuilder.Entity("Domain.Entities.ProfessionalOrderIgnore", b =>
        {
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professionalId");
            b.Property<string>("OrderId").IsRequired().HasColumnName("orderId");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.HasKey("ProfessionalId", "OrderId");
            b.ToTable("ProfessionalOrderIgnore");
        });

        modelBuilder.Entity("Domain.Entities.ProfessionalPortfolio", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.Property<string>("Description").IsRequired(false).HasColumnName("description");
            b.Property<string>("ImageUrl").IsRequired().HasColumnName("imageUrl");
            b.Property<int?>("OrderIndex").HasColumnName("orderIndex");
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professionalId");
            b.Property<string>("Title").IsRequired(false).HasColumnName("title");
            b.HasKey("Id");
            b.HasIndex("ProfessionalId").HasDatabaseName("IX_ProfessionalPortfolio_professionalId");
            b.ToTable("ProfessionalPortfolio");
        });

        modelBuilder.Entity("Domain.Entities.ProfessionalService", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<string>("Descricao").IsRequired(false).HasColumnName("descricao");
            b.Property<string>("NomeServico").IsRequired().HasColumnName("nomeServico");
            b.Property<double?>("Preco").HasColumnName("preco");
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professionalId");
            b.Property<string>("ServiceId").IsRequired().HasColumnName("serviceId");
            b.Property<int?>("TierId").HasColumnName("tierId");
            b.Property<string>("ContractMode").IsRequired(false).HasColumnName("contractMode");
            b.Property<int?>("DurationMinutes").HasColumnName("durationMinutes");
            b.Property<string>("IncludesDescription").IsRequired(false).HasColumnName("includesDescription");
            b.Property<string>("ExcludesDescription").IsRequired(false).HasColumnName("excludesDescription");
            b.Property<bool?>("MaterialIncluded").HasColumnName("materialIncluded");
            b.Property<int?>("VisitFeeCents").HasColumnName("visitFeeCents");
            b.Property<int?>("MinLeadTimeMinutes").HasColumnName("minLeadTimeMinutes");
            b.Property<string>("TipoContratacao").IsRequired(false).HasColumnName("tipoContratacao");
            b.HasKey("Id");
            b.HasIndex("ProfessionalId").HasDatabaseName("IX_ProfessionalService_professionalId");
            b.HasIndex("ServiceId").HasDatabaseName("IX_ProfessionalService_serviceId");
            b.ToTable("ProfessionalService");
        });

        modelBuilder.Entity("Domain.Entities.ProfessionalZone", b =>
        {
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professionalId");
            b.Property<string>("ZoneId").IsRequired().HasColumnName("zoneId");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.HasKey("ProfessionalId", "ZoneId");
            b.HasIndex("ZoneId").HasDatabaseName("IX_ProfessionalZone_zoneId");
            b.ToTable("ProfessionalZone");
        });

        modelBuilder.Entity("Domain.Entities.Dispute", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<string>("OrderId").IsRequired().HasColumnName("order_id");
            b.Property<string>("ClientId").IsRequired().HasColumnName("client_id");
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professional_id");
            b.Property<string>("Reason").IsRequired().HasColumnName("reason");
            b.Property<string>("Description").IsRequired(false).HasColumnName("description");
            b.Property<string>("EvidenceUrls").IsRequired(false).HasColumnName("evidence_urls").HasColumnType("jsonb");
            b.Property<string>("ProfessionalResponse").IsRequired(false).HasColumnName("professional_response");
            b.Property<string>("ProfessionalEvidenceUrls").IsRequired(false).HasColumnName("professional_evidence_urls").HasColumnType("jsonb");
            b.Property<string>("Resolution").IsRequired(false).HasColumnName("resolution");
            b.Property<string>("ResolvedBy").IsRequired(false).HasColumnName("resolved_by");
            b.Property<int?>("RefundAmountCents").HasColumnName("refund_amount_cents");
            b.Property<string>("Status").IsRequired().HasColumnName("status").HasDefaultValue("opened");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("created_at");
            b.Property<DateTime?>("ResolvedAt").HasColumnName("resolved_at");
            b.HasKey("Id");
            b.HasIndex("OrderId").IsUnique().HasDatabaseName("IX_dispute_order_id");
            b.HasIndex("ProfessionalId").HasDatabaseName("IX_dispute_professional_id");
            b.HasIndex("ClientId").HasDatabaseName("IX_dispute_client_id");
            b.HasIndex("Status").HasDatabaseName("IX_dispute_status");
            b.ToTable("dispute");
        });

        modelBuilder.Entity("Domain.Entities.ProfessionalMpAccount", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professional_id");
            b.Property<string>("MpUserId").IsRequired().HasColumnName("mp_user_id");
            b.Property<string>("MpAccessToken").IsRequired().HasColumnName("mp_access_token");
            b.Property<string>("MpRefreshToken").IsRequired().HasColumnName("mp_refresh_token");
            b.Property<DateTime>("MpTokenExpiresAt").IsRequired().HasColumnName("mp_token_expires_at");
            b.Property<string>("MpScope").IsRequired(false).HasColumnName("mp_scope");
            b.Property<bool>("MpLiveMode").IsRequired().HasColumnName("mp_live_mode").HasDefaultValue(false);
            b.Property<string>("Status").IsRequired().HasColumnName("status").HasDefaultValue("active");
            b.Property<DateTime>("ConnectedAt").IsRequired().HasColumnName("connected_at");
            b.Property<DateTime?>("LastRefreshedAt").HasColumnName("last_refreshed_at");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("created_at");
            b.Property<DateTime>("UpdatedAt").IsRequired().HasColumnName("updated_at");
            b.HasKey("Id");
            b.HasIndex("ProfessionalId").IsUnique().HasDatabaseName("IX_professional_mp_account_professional_id");
            b.HasIndex("MpTokenExpiresAt", "Status")
                .HasFilter("status = 'active'")
                .HasDatabaseName("IX_professional_mp_account_expires_status");
            b.ToTable("professional_mp_account");
        });

        modelBuilder.Entity("Domain.Entities.WebhookEvent", b =>
        {
            b.Property<string>("Provider").IsRequired().HasColumnName("provider");
            b.Property<string>("EventId").IsRequired().HasColumnName("event_id");
            b.Property<string>("Topic").IsRequired().HasColumnName("topic");
            b.Property<string>("Action").IsRequired(false).HasColumnName("action");
            b.Property<string>("RawPayload").IsRequired().HasColumnName("raw_payload");
            b.Property<string>("Status").IsRequired().HasColumnName("status").HasDefaultValue("received");
            b.Property<string>("ErrorMessage").IsRequired(false).HasColumnName("error_message");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("created_at");
            b.Property<DateTime?>("ProcessedAt").HasColumnName("processed_at");
            b.HasKey("Provider", "EventId");
            b.HasIndex("Status", "CreatedAt")
                .HasFilter("status IN ('failed', 'received')")
                .HasDatabaseName("IX_webhook_events_status_created");
            b.ToTable("webhook_events");
        });

        modelBuilder.Entity("Domain.Entities.Review", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<string>("ClientId").IsRequired().HasColumnName("clientId");
            b.Property<string>("Comment").IsRequired(false).HasColumnName("comment");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.Property<string>("OrderId").IsRequired().HasColumnName("orderId");
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professionalId");
            b.Property<int>("Rating").IsRequired().HasColumnName("rating");
            // Phase 3: expanded categories
            b.Property<int?>("PunctualityRating").HasColumnName("punctualityRating");
            b.Property<int?>("QualityRating").HasColumnName("qualityRating");
            b.Property<int?>("CommunicationRating").HasColumnName("communicationRating");
            b.Property<int?>("CleanlinessRating").HasColumnName("cleanlinessRating");
            // Phase 3: photos
            b.Property<string>("PhotoUrls").IsRequired(false).HasColumnName("photoUrls").HasColumnType("jsonb");
            // Phase 3: professional reviews client
            b.Property<string>("ProfessionalReviewOfClient").IsRequired(false).HasColumnName("professionalReviewOfClient");
            b.Property<int?>("ProfessionalRatingOfClient").HasColumnName("professionalRatingOfClient");
            // Phase 3: double-blind
            b.Property<DateTime?>("ClientVisibleAt").HasColumnName("clientVisibleAt");
            b.Property<DateTime?>("ProfessionalVisibleAt").HasColumnName("professionalVisibleAt");
            // Phase 3: verified
            b.Property<bool>("IsVerified").IsRequired().HasColumnName("isVerified").HasDefaultValue(false);
            b.HasKey("Id");
            b.HasIndex("ClientId", "CreatedAt").HasDatabaseName("IX_Review_clientId_createdAt");
            b.HasIndex("OrderId").IsUnique();
            b.HasIndex("ProfessionalId").HasDatabaseName("IX_Review_professionalId");
            b.ToTable("Review");
        });

        modelBuilder.Entity("Domain.Entities.Service", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.Property<string>("Icon").IsRequired(false).HasColumnName("icon");
            b.Property<string>("Name").IsRequired().HasColumnName("name");
            b.Property<string>("CategoryId").IsRequired(false).HasColumnName("categoryId");
            b.Property<int?>("TierId").HasColumnName("tierId");
            b.HasKey("Id");
            b.ToTable("Service");
        });

        modelBuilder.Entity("Domain.Entities.ServiceTier", b =>
        {
            b.Property<int>("Id").HasColumnName("id").ValueGeneratedOnAdd()
                .HasAnnotation("Npgsql:ValueGenerationStrategy", Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            b.Property<string>("Name").IsRequired().HasColumnName("name");
            b.Property<string>("Code").IsRequired().HasColumnName("code");
            b.Property<bool>("AllowBookingDirect").IsRequired().HasColumnName("allow_booking_direct");
            b.Property<bool>("RequiresProposal").IsRequired().HasColumnName("requires_proposal");
            b.Property<bool>("RequiresChat").IsRequired().HasColumnName("requires_chat");
            b.Property<string[]>("AllowedPriceFormats").IsRequired().HasColumnName("allowed_price_formats").HasColumnType("text[]");
            b.Property<int>("DefaultSignalPercent").IsRequired().HasColumnName("default_signal_percent").HasDefaultValue(0);
            b.Property<int>("MaxInstallments").IsRequired().HasColumnName("max_installments").HasDefaultValue(1);
            b.Property<string>("CancellationRules").IsRequired(false).HasColumnName("cancellation_rules").HasColumnType("jsonb");
            b.HasKey("Id");
            b.HasIndex("Code").IsUnique();
            b.ToTable("service_tier");
        });

        modelBuilder.Entity("Domain.Entities.ServiceCategory", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<string>("Name").IsRequired().HasColumnName("name");
            b.Property<string>("Icon").IsRequired(false).HasColumnName("icon");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("created_at");
            b.HasKey("Id");
            b.HasIndex("Name");
            b.ToTable("service_category");
        });

        modelBuilder.Entity("Domain.Entities.User", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.Property<string>("Email").IsRequired().HasColumnName("email");
            b.Property<string>("Name").IsRequired().HasColumnName("name");
            b.Property<string>("Phone").IsRequired(false).HasColumnName("phone");
            b.Property<string>("Role").IsRequired().HasColumnName("role");
            b.Property<string>("ZoneId").IsRequired(false).HasColumnName("zoneId");
            b.HasKey("Id");
            b.HasIndex("Email").IsUnique();
            b.HasIndex("ZoneId").HasDatabaseName("IX_User_zoneId");
            b.ToTable("User");
        });

        modelBuilder.Entity("Domain.Entities.Zone", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<bool>("Active").IsRequired().HasColumnName("active").HasDefaultValue(true);
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.Property<string>("Name").IsRequired().HasColumnName("name");
            b.HasKey("Id");
            b.HasIndex("Name").IsUnique();
            b.ToTable("Zone");
        });
#pragma warning restore 612, 618
    }
}
