// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Domain.Entities.Appointment", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<string>("ClientId").IsRequired(false).HasColumnName("clientId");
            b.Property<DateTime>("EndsAt").IsRequired().HasColumnName("endsAt");
            b.Property<string>("Location").IsRequired(false).HasColumnName("location");
            b.Property<string>("Notes").IsRequired(false).HasColumnName("notes");
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professionalId");
            b.Property<string>("ServiceId").IsRequired(false).HasColumnName("serviceId");
            b.Property<DateTime>("StartsAt").IsRequired().HasColumnName("startsAt");
            b.Property<string>("Status").IsRequired().HasColumnName("status");
            b.HasKey("Id");
            b.HasIndex("ClientId").HasDatabaseName("IX_Appointment_clientId");
            b.HasIndex("ProfessionalId").HasDatabaseName("IX_Appointment_professionalId");
            b.HasIndex("ProfessionalId", "StartsAt", "Status").HasDatabaseName("IX_Appointment_professionalId_startsAt_status");
            b.ToTable("Appointment");
        });

        modelBuilder.Entity("Domain.Entities.Conversation", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<string>("ClientId").IsRequired().HasColumnName("clientId");
            b.Property<DateTime?>("ClientLastReadAt").HasColumnName("clientLastReadAt");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.Property<string>("OrderId").IsRequired(false).HasColumnName("orderId");
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professionalId");
            b.Property<DateTime?>("ProfessionalLastReadAt").HasColumnName("professionalLastReadAt");
            b.HasKey("Id");
            b.HasIndex("ClientId").HasDatabaseName("IX_Conversation_clientId");
            b.HasIndex("ClientId", "ProfessionalId").HasDatabaseName("IX_Conversation_clientId_professionalId");
            b.HasIndex("OrderId").IsUnique();
            b.HasIndex("ProfessionalId").HasDatabaseName("IX_Conversation_professionalId");
            b.ToTable("Conversation");
        });

        modelBuilder.Entity("Domain.Entities.Message", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<string>("ConversationId").IsRequired().HasColumnName("conversationId");
            b.Property<string>("SenderId").IsRequired().HasColumnName("senderId");
            b.Property<DateTime>("SentAt").IsRequired().HasColumnName("sentAt");
            b.Property<string>("Text").IsRequired().HasColumnName("text");
            b.HasKey("Id");
            b.HasIndex("ConversationId").HasDatabaseName("IX_Message_conversationId");
            b.HasIndex("ConversationId", "SentAt").HasDatabaseName("IX_Message_conversationId_sentAt");
            b.ToTable("Message");
        });

        modelBuilder.Entity("Domain.Entities.Order", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<string>("ClientId").IsRequired().HasColumnName("clientId");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.Property<DateTime?>("Date").HasColumnName("date");
            b.Property<string>("Description").IsRequired(false).HasColumnName("description");
            b.Property<string>("Location").IsRequired(false).HasColumnName("location");
            b.Property<string>("ServiceId").IsRequired().HasColumnName("serviceId");
            b.Property<string>("Status").IsRequired().HasColumnName("status").HasDefaultValue("aberto");
            b.HasKey("Id");
            b.HasIndex("ClientId").HasDatabaseName("IX_Order_clientId");
            b.HasIndex("ClientId", "CreatedAt").HasDatabaseName("IX_Order_clientId_createdAt");
            b.HasIndex("ServiceId").HasDatabaseName("IX_Order_serviceId");
            b.HasIndex("Status").HasDatabaseName("IX_Order_status");
            b.ToTable("Order");
        });

        modelBuilder.Entity("Domain.Entities.Professional", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<bool>("Active").IsRequired().HasColumnName("active").HasDefaultValue(true);
            b.Property<bool?>("AllowInstantBooking").HasColumnName("allowInstantBooking");
            b.Property<string>("AvatarUrl").IsRequired(false).HasColumnName("avatarUrl");
            b.Property<string>("AvailabilityText").IsRequired(false).HasColumnName("availabilityText");
            b.Property<string>("Bio").IsRequired(false).HasColumnName("bio");
            b.Property<int>("CompletedJobsCount").IsRequired().HasColumnName("completedJobsCount").HasDefaultValue(0);
            b.Property<int?>("LeadTimeMinutes").HasColumnName("leadTimeMinutes");
            b.Property<int?>("MaxAdvanceDays").HasColumnName("maxAdvanceDays");
            b.Property<double?>("Rating").HasColumnName("rating");
            b.Property<int?>("SlotMinutes").HasColumnName("slotMinutes");
            b.Property<string>("UserId").IsRequired().HasColumnName("userId");
            b.Property<string>("EntityType").IsRequired(false).HasColumnName("entityType");
            b.Property<string>("DocumentNumber").IsRequired(false).HasColumnName("documentNumber");
            b.Property<int?>("YearsOfExperience").HasColumnName("yearsOfExperience");
            b.Property<string[]>("Specialties").HasColumnName("specialties").HasColumnType("text[]");
            b.Property<double?>("ResponseRate").HasColumnName("responseRate");
            b.Property<int?>("AvgResponseTimeMinutes").HasColumnName("avgResponseTimeMinutes");
            b.Property<double?>("CompletionRate").HasColumnName("completionRate");
            b.Property<string>("VerificationStatus").IsRequired().HasColumnName("verificationStatus").HasDefaultValue("pending");
            b.Property<string>("Badges").IsRequired(false).HasColumnName("badges");
            b.Property<int>("BufferMinutes").IsRequired().HasColumnName("bufferMinutes").HasDefaultValue(0);
            b.HasKey("Id");
            b.HasIndex("Active", "Rating").HasDatabaseName("IX_Professional_active_rating");
            b.HasIndex("UserId").HasDatabaseName("IX_Professional_userId");
            b.ToTable("Professional");
        });

        modelBuilder.Entity("Domain.Entities.ProfessionalAvailability", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<bool>("Active").IsRequired().HasColumnName("active").HasDefaultValue(true);
            b.Property<int>("EndMinutes").IsRequired().HasColumnName("endMinutes");
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professionalId");
            b.Property<int>("StartMinutes").IsRequired().HasColumnName("startMinutes");
            b.Property<int>("Weekday").IsRequired().HasColumnName("weekday");
            b.HasKey("Id");
            b.HasIndex("ProfessionalId", "Weekday").HasDatabaseName("IX_ProfessionalAvailability_professionalId_weekday");
            b.ToTable("ProfessionalAvailability");
        });

        modelBuilder.Entity("Domain.Entities.ProfessionalBlock", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.Property<DateTime>("EndsAt").IsRequired().HasColumnName("endsAt");
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professionalId");
            b.Property<string>("Reason").IsRequired(false).HasColumnName("reason");
            b.Property<DateTime>("StartsAt").IsRequired().HasColumnName("startsAt");
            b.HasKey("Id");
            b.HasIndex("ProfessionalId", "StartsAt", "EndsAt").HasDatabaseName("IX_ProfessionalBlock_professionalId_startsAt_endsAt");
            b.ToTable("ProfessionalBlock");
        });

        modelBuilder.Entity("Domain.Entities.ProfessionalOrderIgnore", b =>
        {
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professionalId");
            b.Property<string>("OrderId").IsRequired().HasColumnName("orderId");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.HasKey("ProfessionalId", "OrderId");
            b.ToTable("ProfessionalOrderIgnore");
        });

        modelBuilder.Entity("Domain.Entities.ProfessionalPortfolio", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.Property<string>("Description").IsRequired(false).HasColumnName("description");
            b.Property<string>("ImageUrl").IsRequired().HasColumnName("imageUrl");
            b.Property<int?>("OrderIndex").HasColumnName("orderIndex");
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professionalId");
            b.Property<string>("Title").IsRequired(false).HasColumnName("title");
            b.HasKey("Id");
            b.HasIndex("ProfessionalId").HasDatabaseName("IX_ProfessionalPortfolio_professionalId");
            b.ToTable("ProfessionalPortfolio");
        });

        modelBuilder.Entity("Domain.Entities.ProfessionalService", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<string>("Descricao").IsRequired(false).HasColumnName("descricao");
            b.Property<string>("NomeServico").IsRequired().HasColumnName("nomeServico");
            b.Property<double>("Preco").IsRequired().HasColumnName("preco");
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professionalId");
            b.Property<string>("ServiceId").IsRequired().HasColumnName("serviceId");
            b.Property<int?>("TierId").HasColumnName("tierId");
            b.Property<string>("ContractMode").IsRequired(false).HasColumnName("contractMode");
            b.Property<int?>("DurationMinutes").HasColumnName("durationMinutes");
            b.Property<string>("IncludesDescription").IsRequired(false).HasColumnName("includesDescription");
            b.Property<string>("ExcludesDescription").IsRequired(false).HasColumnName("excludesDescription");
            b.Property<bool?>("MaterialIncluded").HasColumnName("materialIncluded");
            b.Property<int?>("VisitFeeCents").HasColumnName("visitFeeCents");
            b.Property<int?>("MinLeadTimeMinutes").HasColumnName("minLeadTimeMinutes");
            b.HasKey("Id");
            b.HasIndex("ProfessionalId").HasDatabaseName("IX_ProfessionalService_professionalId");
            b.HasIndex("ServiceId").HasDatabaseName("IX_ProfessionalService_serviceId");
            b.ToTable("ProfessionalService");
        });

        modelBuilder.Entity("Domain.Entities.ProfessionalZone", b =>
        {
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professionalId");
            b.Property<string>("ZoneId").IsRequired().HasColumnName("zoneId");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.HasKey("ProfessionalId", "ZoneId");
            b.HasIndex("ZoneId").HasDatabaseName("IX_ProfessionalZone_zoneId");
            b.ToTable("ProfessionalZone");
        });

        modelBuilder.Entity("Domain.Entities.Review", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<string>("ClientId").IsRequired().HasColumnName("clientId");
            b.Property<string>("Comment").IsRequired(false).HasColumnName("comment");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.Property<string>("OrderId").IsRequired().HasColumnName("orderId");
            b.Property<string>("ProfessionalId").IsRequired().HasColumnName("professionalId");
            b.Property<int>("Rating").IsRequired().HasColumnName("rating");
            b.HasKey("Id");
            b.HasIndex("ClientId", "CreatedAt").HasDatabaseName("IX_Review_clientId_createdAt");
            b.HasIndex("OrderId").IsUnique();
            b.HasIndex("ProfessionalId").HasDatabaseName("IX_Review_professionalId");
            b.ToTable("Review");
        });

        modelBuilder.Entity("Domain.Entities.Service", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.Property<string>("Icon").IsRequired(false).HasColumnName("icon");
            b.Property<string>("Name").IsRequired().HasColumnName("name");
            b.Property<string>("CategoryId").IsRequired(false).HasColumnName("categoryId");
            b.Property<int?>("TierId").HasColumnName("tierId");
            b.HasKey("Id");
            b.ToTable("Service");
        });

        modelBuilder.Entity("Domain.Entities.ServiceTier", b =>
        {
            b.Property<int>("Id").HasColumnName("id").ValueGeneratedOnAdd()
                .HasAnnotation("Npgsql:ValueGenerationStrategy", Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            b.Property<string>("Name").IsRequired().HasColumnName("name");
            b.Property<string>("Code").IsRequired().HasColumnName("code");
            b.Property<bool>("AllowBookingDirect").IsRequired().HasColumnName("allow_booking_direct");
            b.Property<bool>("RequiresProposal").IsRequired().HasColumnName("requires_proposal");
            b.Property<bool>("RequiresChat").IsRequired().HasColumnName("requires_chat");
            b.Property<string[]>("AllowedPriceFormats").IsRequired().HasColumnName("allowed_price_formats").HasColumnType("text[]");
            b.Property<int>("DefaultSignalPercent").IsRequired().HasColumnName("default_signal_percent").HasDefaultValue(0);
            b.Property<int>("MaxInstallments").IsRequired().HasColumnName("max_installments").HasDefaultValue(1);
            b.Property<string>("CancellationRules").IsRequired(false).HasColumnName("cancellation_rules").HasColumnType("jsonb");
            b.HasKey("Id");
            b.HasIndex("Code").IsUnique();
            b.ToTable("service_tier");
        });

        modelBuilder.Entity("Domain.Entities.ServiceCategory", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<string>("Name").IsRequired().HasColumnName("name");
            b.Property<string>("Icon").IsRequired(false).HasColumnName("icon");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("created_at");
            b.HasKey("Id");
            b.HasIndex("Name");
            b.ToTable("service_category");
        });

        modelBuilder.Entity("Domain.Entities.User", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.Property<string>("Email").IsRequired().HasColumnName("email");
            b.Property<string>("Name").IsRequired().HasColumnName("name");
            b.Property<string>("Phone").IsRequired(false).HasColumnName("phone");
            b.Property<string>("Role").IsRequired().HasColumnName("role");
            b.Property<string>("ZoneId").IsRequired(false).HasColumnName("zoneId");
            b.HasKey("Id");
            b.HasIndex("Email").IsUnique();
            b.HasIndex("ZoneId").HasDatabaseName("IX_User_zoneId");
            b.ToTable("User");
        });

        modelBuilder.Entity("Domain.Entities.Zone", b =>
        {
            b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
            b.Property<bool>("Active").IsRequired().HasColumnName("active").HasDefaultValue(true);
            b.Property<DateTime>("CreatedAt").IsRequired().HasColumnName("createdAt");
            b.Property<string>("Name").IsRequired().HasColumnName("name");
            b.HasKey("Id");
            b.HasIndex("Name").IsUnique();
            b.ToTable("Zone");
        });
#pragma warning restore 612, 618
    }
}
