namespace Domain.Entities;

public sealed record Professional(
    string Id,
    string UserId,
    string? Bio,
    double? Rating,
    bool Active,
    string? AvatarUrl,
    string? AvailabilityText,
    int CompletedJobsCount,
    int? SlotMinutes,
    int? LeadTimeMinutes,
    int? MaxAdvanceDays,
    bool? AllowInstantBooking,
    string? EntityType = null,
    string? DocumentNumber = null,
    int? YearsOfExperience = null,
    string[]? Specialties = null,
    double? ResponseRate = null,
    int? AvgResponseTimeMinutes = null,
    double? CompletionRate = null,
    string VerificationStatus = "pending",
    string? Badges = null,
    int BufferMinutes = 0,
    bool MpConnected = false,
    DateTime? MpConnectedAt = null);
